### ISSUE TITLE
File collision with Ruby dotenv on /usr/bin/dotenv

### ISSUE THREAD

**Issue by hartwork** [theskumar/python-dotenv#339]
Hi!

It [came to my attention](https://bugs.gentoo.org/798648) that both [Ruby dotenv](https://github.com/bkeepers/dotenv) and Python dotenv want to install/own file `/usr/bin/dotenv`. To a Linux distribution that wants (or needs) to package both of these, that's a problem because we cannot install both packages at the same time then which affects all reverse dependencies. Any thoughts?

Thanks and best, Sebastian

**Comment by bbc2** [comment]
Perhaps it would make sense to install it as `/usr/bin/python-dotenv`?  That's what Debian does: https://packages.debian.org/buster/all/python3-dotenv/filelist but I don't know how they do it.

I'm not very familiar with that kind of situation.  Let me know if there's something we can do to improve in the package.  I'm not sure we should rename the `dotenv` executable installed by default (e.g. with `pip install python-dotenv[cli]`).

**Comment by hartwork** [comment]
> Perhaps it would make sense to install it as `/usr/bin/python-dotenv`? That's what Debian does: https://packages.debian.org/buster/all/python3-dotenv/filelist but I don't know how they do it.

Debian has this code in a Makefile named `debian/rules` of the [related packaging](http://deb.debian.org/debian/pool/main/p/python-dotenv/python-dotenv_0.15.0-1.debian.tar.xz) that does the renaming:
```makefile
override_dh_auto_install:
	find . -name '.nx_file' -delete
	dh_auto_install
	mv debian/python3-dotenv/usr/bin/dotenv debian/python3-dotenv/usr/bin/python-dotenv
```

If you're up for adopting that naming upstream, it would fix the issue and users of Debian and Debian-based distros like Ubuntu will not experience any change. It would also communicate clearly, which dotenv users are dealing with. What do you think?

**Comment by bbc2** [comment]
> 	find . -name '.nx_file' -delete

Ouch, I hadn't realized this was a problem downstream.  #340 should fix it.

> If you're up for adopting that naming upstream, it would fix the issue and users of Debian and Debian-based distros like Ubuntu will not experience any change. It would also communicate clearly, which dotenv users are dealing with. What do you think?

It could be a good thing overall but it's not an obvious benefit for Python developers. In any case, it wouldn't happen overnight.  If we do this, there will be a transition period with two executables available, so my advice would be to handle the renaming downstream in the meantime.

**Comment by hartwork** [comment]
> [..] so my advice would be to handle the renaming downstream in the meantime.

Done (https://github.com/gentoo/gentoo/commit/d4beda25f7a27938194241dfaaef1ffafb12c8ce)

**Comment by hartwork** [comment]
Any news on a potential rename of the CLI command?

**Comment by jhgit** [comment]
>     * Fedora: `python-dotenv+cli` with command `dotenv` ([source](https://koji.fedoraproject.org/koji/rpminfo?rpmID=27590807))

There is also a godotenv package (no conflict due to the name of the CLI tool being `bin/godotenv`).  Fedora does not seem to have a package for the rubygem flavor of dotenv.

>     * FreeBSD: `py38-python-dotenv` with commands `dotenv` and `dotenv-3.8` ([source](https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/py38-python-dotenv-0.19.1.txz))

FreeBSD: The ports `www/python-dotenv` and `misc/rubygem-dotenv` have a documented and unresolved conflict due to both wanting to install bin/dotenv.  So you can't install them both at the time of this writing.  The ruby flavor was added in 2013.  The python flavor was added in 2018.

**Comment by jhgit** [comment]
The `dotenv` script in the python-dotenv package appears to be more featureful than the rubygem version (list, set, get, run for the python flavor vs. just [essentially] run for the ruby flavor).  But the two versions are certainly not drop-in compatible.

I don't know any software that is dependent on the `bin/dotenv` script (vs. the python or rubygem library).  That doesn't mean there isn't a dependency - I just have not seen one yet.

I think it would be helpful to just rename the `dotenv` script in python-dotenv to `py-dotenv` or `dotenv-py`.  But I don't know if any consumers would be affected.

Regarding provenance, if you just look at history of "first commit" in git repos, the ruby version precedes the python version (2012 vs 2013).

**Comment by jhgit** [comment]
This is still an issue.  Please at least install `py-dotenv` or `dotenv-py`, and optionally support a link from`dotenv` to either of those.

As precendence, there is a golang version of dotenv installed as `godotenv`.

I understand this version of dotenv for python came about as a replacement for the original dotenv for python that was abanadoned.  The growing unanswered issues list and pull requests here is not a good sign (not to mention the outdated home page which does not reflect the latest release).  Is this project heading down the same path?  If this is still being actively maintained, please spend a little time to review issues & pull requests. @bbc2 @theskumar

**Comment by jhgit** [comment]
While considering collisions with other dotenv CLI implementations, maybe consider making the `run` subcommand be the default if it is still planned to install a CLI utility named `dotenv`.  That is if invoked as `dotenv uname`, it runs the `uname` command after injecting .env file contents into the environment, just as `dotenv run uname` does now.

Or perhaps make the subcommands be more explicitly optional (e.g., `--run`, `--list`, etc.), and make the default invocation match other implementations so that the following works: `dotenv <command> <args ..>` by default.

**Comment by jhgit** [comment]
Fair point.  It was mostly meant to be thought provoking.  Changing the command line syntax should be considered carefully, of course.  Sorry to piggyback on the main issue at hand.
